version: "2"

run:
  timeout:     5m
  concurrency: 4

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

linters:
  enable:
    - govet
    - unused
    - gocyclo
    - errcheck
    - staticcheck

issues:
  max-same-issues:       30
  max-issues-per-linter: 30
