version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt

linters:
  default: standard
  enable:
    - gocyclo
    - ineffassign
    - misspell
  settings:
    gocyclo:
      min-complexity: 15

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
