services:
  - name:       "first service"
    host:       "localhost:1000"
    repository: "https://repo.com/first-service"
  - name:       "second service"
    host:       "localhost:2000"
    repository: "https://repo.com/second-service"
  - name:       "third service"
    host:       "localhost:3000"
    repository: "https://repo.com/third-service"
resultsDir:     "."
htmlReportDir:  "."
jsonReportDir:  "."
htmlReportFile: "index.html"
jsonReportFile: "coverage-report.json"
