services:
  - key:        "first-service"
    name:       "first service"
    host:       "localhost:1000"
    repository: "https://repo.com/first-service"
  - key:        "second-service"
    name:       "second service"
    host:       "localhost:2000"
    repository: "https://repo.com/second-service"
  - key:        "third-service"
    name:       "third service"
    host:       "localhost:3000"
    repository: "https://repo.com/third-service"
resultsDir:            "."
historyDir:            "."
historyFile:           "coverage-history.json"
htmlReportDir:         "."
jsonReportDir:         "."
htmlReportFile:        "index.html"
jsonReportFile:        "coverage-report.json"
historyRetentionLimit: 30
